# The URL the site will be built for
base_url = "https://vishalkrkamat.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

title = "vishalkrkamat"
description = "Projects, learnings, and thoughts."
default_language = "en"
#theme = "anemone"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Taxonomies
taxonomies = [{ name = "tags" }]

# taxonomies = [
#   { name = "tags", rss = true, paginate_by = 10 }
# ]

[markdown]
#highlight_theme = "dracula"# Whether to do syntax highlighting

[markdown.highlighting]
light_theme = "github-light"                                                                                     
dark_theme = "github-dark"

[extra]
author = "Speyll"
favicon = "favicon.ico"
list_pages = true
twitter_card = true
enable_search = true
job_seeking = false

## Navigation
header_nav = [
  # { url = "/", name_en = "/home/", name_fr = "/accueil/" },
  { url = "/about", name_en = "/about/", name_fr = "/concernant/" },
  { url = "/projects", name_en = "/projects/", name_fr = "/projects/" },
  { url = "/blog", name_en = "/blog/", name_fr = "/blog/" }
]

[extra.linkedin]
username = "vishalkrkamat"
# Put all your custom variables here
